@baseUrl = http://localhost:8080

### Login with One Time Token (Success)
# Expect: 200 OK + Sets JSESSIONID cookie
# Note: token must be valid and exist in DB
POST {{baseUrl}}/api/login/ott
Content-Type: application/x-www-form-urlencoded

token=6f9b6201-f949-48cd-9db6-a6ef0bcdbb5b

### Login with Invalid Token (Failure)
# Expect: 401 Unauthorized (JSON)
POST {{baseUrl}}/api/login/ott
Content-Type: application/x-www-form-urlencoded

token=INVALID_TOKEN
